packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "esbuild"
  - "sharp"
  - "workerd"
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  sharp: true
  workerd: true
